// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/jp/docs/standard-phrases-window-and-history-window": {
    params: {};
  };
  "/docs/standard-phrases-window-and-history-window": {
    params: {};
  };
  "/jp/docs/export-and-import-of-standard-phrases": {
    params: {};
  };
  "/jp/docs/standard-phrases-and-copy-history": {
    params: {};
  };
  "/docs/export-and-import-of-standard-phrases": {
    params: {};
  };
  "/docs/standard-phrases-and-copy-history": {
    params: {};
  };
  "/jp/docs/how-to-use-quick-overlay": {
    params: {};
  };
  "/jp/docs/upgrade-history-data": {
    params: {};
  };
  "/docs/how-to-use-quick-overlay": {
    params: {};
  };
  "/docs/upgrade-history-data": {
    params: {};
  };
  "/jp/docs/notifications": {
    params: {};
  };
  "/jp/docs/useful-usages": {
    params: {};
  };
  "/docs/notifications": {
    params: {};
  };
  "/docs/useful-usages": {
    params: {};
  };
  "/jp/docs/settings": {
    params: {};
  };
  "/jp/privacy-policy": {
    params: {};
  };
  "/jp/release-notes": {
    params: {};
  };
  "/jp/docs/news": {
    params: {};
  };
  "/docs/settings": {
    params: {};
  };
  "/jp/docs/faq": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
  "/release-notes": {
    params: {};
  };
  "/jp/support": {
    params: {};
  };
  "/docs/news": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/docs/faq": {
    params: {};
  };
  "/jp/docs": {
    params: {};
  };
  "/support": {
    params: {};
  };
  "/docs": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/jp": {
    params: {};
  };
  "/_image/*": {
    params: {
      "*": string;
    };
  };
  "/jp/*": {
    params: {
      "*": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/jp/docs/standard-phrases-window-and-history-window" | "/docs/standard-phrases-window-and-history-window" | "/jp/docs/export-and-import-of-standard-phrases" | "/jp/docs/standard-phrases-and-copy-history" | "/docs/export-and-import-of-standard-phrases" | "/docs/standard-phrases-and-copy-history" | "/jp/docs/how-to-use-quick-overlay" | "/jp/docs/upgrade-history-data" | "/docs/how-to-use-quick-overlay" | "/docs/upgrade-history-data" | "/jp/docs/notifications" | "/jp/docs/useful-usages" | "/docs/notifications" | "/docs/useful-usages" | "/jp/docs/settings" | "/jp/privacy-policy" | "/jp/release-notes" | "/jp/docs/news" | "/docs/settings" | "/jp/docs/faq" | "/privacy-policy" | "/release-notes" | "/jp/support" | "/docs/news" | "/sitemap.xml" | "/docs/faq" | "/jp/docs" | "/support" | "/docs" | "/robots.txt" | "/jp" | "/_image/*" | "/jp/*" | "/*";
  };
  "routes/[jp].[docs].[standard-phrases-window-and-history-window]._index.tsx": {
    id: "routes/[jp].[docs].[standard-phrases-window-and-history-window]._index";
    page: "/jp/docs/standard-phrases-window-and-history-window";
  };
  "routes/[docs].[standard-phrases-window-and-history-window]._index.tsx": {
    id: "routes/[docs].[standard-phrases-window-and-history-window]._index";
    page: "/docs/standard-phrases-window-and-history-window";
  };
  "routes/[jp].[docs].[export-and-import-of-standard-phrases]._index.tsx": {
    id: "routes/[jp].[docs].[export-and-import-of-standard-phrases]._index";
    page: "/jp/docs/export-and-import-of-standard-phrases";
  };
  "routes/[jp].[docs].[standard-phrases-and-copy-history]._index.tsx": {
    id: "routes/[jp].[docs].[standard-phrases-and-copy-history]._index";
    page: "/jp/docs/standard-phrases-and-copy-history";
  };
  "routes/[docs].[export-and-import-of-standard-phrases]._index.tsx": {
    id: "routes/[docs].[export-and-import-of-standard-phrases]._index";
    page: "/docs/export-and-import-of-standard-phrases";
  };
  "routes/[docs].[standard-phrases-and-copy-history]._index.tsx": {
    id: "routes/[docs].[standard-phrases-and-copy-history]._index";
    page: "/docs/standard-phrases-and-copy-history";
  };
  "routes/[jp].[docs].[how-to-use-quick-overlay]._index.tsx": {
    id: "routes/[jp].[docs].[how-to-use-quick-overlay]._index";
    page: "/jp/docs/how-to-use-quick-overlay";
  };
  "routes/[jp].[docs].[upgrade-history-data]._index.tsx": {
    id: "routes/[jp].[docs].[upgrade-history-data]._index";
    page: "/jp/docs/upgrade-history-data";
  };
  "routes/[docs].[how-to-use-quick-overlay]._index.tsx": {
    id: "routes/[docs].[how-to-use-quick-overlay]._index";
    page: "/docs/how-to-use-quick-overlay";
  };
  "routes/[docs].[upgrade-history-data]._index.tsx": {
    id: "routes/[docs].[upgrade-history-data]._index";
    page: "/docs/upgrade-history-data";
  };
  "routes/[jp].[docs].[notifications]._index.tsx": {
    id: "routes/[jp].[docs].[notifications]._index";
    page: "/jp/docs/notifications";
  };
  "routes/[jp].[docs].[useful-usages]._index.tsx": {
    id: "routes/[jp].[docs].[useful-usages]._index";
    page: "/jp/docs/useful-usages";
  };
  "routes/[docs].[notifications]._index.tsx": {
    id: "routes/[docs].[notifications]._index";
    page: "/docs/notifications";
  };
  "routes/[docs].[useful-usages]._index.tsx": {
    id: "routes/[docs].[useful-usages]._index";
    page: "/docs/useful-usages";
  };
  "routes/[jp].[docs].[settings]._index.tsx": {
    id: "routes/[jp].[docs].[settings]._index";
    page: "/jp/docs/settings";
  };
  "routes/[jp].[privacy-policy]._index.tsx": {
    id: "routes/[jp].[privacy-policy]._index";
    page: "/jp/privacy-policy";
  };
  "routes/[jp].[release-notes]._index.tsx": {
    id: "routes/[jp].[release-notes]._index";
    page: "/jp/release-notes";
  };
  "routes/[jp].[docs].[news]._index.tsx": {
    id: "routes/[jp].[docs].[news]._index";
    page: "/jp/docs/news";
  };
  "routes/[docs].[settings]._index.tsx": {
    id: "routes/[docs].[settings]._index";
    page: "/docs/settings";
  };
  "routes/[jp].[docs].[faq]._index.tsx": {
    id: "routes/[jp].[docs].[faq]._index";
    page: "/jp/docs/faq";
  };
  "routes/[privacy-policy]._index.tsx": {
    id: "routes/[privacy-policy]._index";
    page: "/privacy-policy";
  };
  "routes/[release-notes]._index.tsx": {
    id: "routes/[release-notes]._index";
    page: "/release-notes";
  };
  "routes/[jp].[support]._index.tsx": {
    id: "routes/[jp].[support]._index";
    page: "/jp/support";
  };
  "routes/[docs].[news]._index.tsx": {
    id: "routes/[docs].[news]._index";
    page: "/docs/news";
  };
  "routes/[sitemap.xml]._index.tsx": {
    id: "routes/[sitemap.xml]._index";
    page: "/sitemap.xml";
  };
  "routes/[docs].[faq]._index.tsx": {
    id: "routes/[docs].[faq]._index";
    page: "/docs/faq";
  };
  "routes/[jp].[docs]._index.tsx": {
    id: "routes/[jp].[docs]._index";
    page: "/jp/docs";
  };
  "routes/[support]._index.tsx": {
    id: "routes/[support]._index";
    page: "/support";
  };
  "routes/[docs]._index.tsx": {
    id: "routes/[docs]._index";
    page: "/docs";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/[jp]._index.tsx": {
    id: "routes/[jp]._index";
    page: "/jp";
  };
  "routes/[_image].$.ts": {
    id: "routes/[_image].$";
    page: "/_image/*";
  };
  "routes/[jp].$.tsx": {
    id: "routes/[jp].$";
    page: "/jp/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/[jp].[docs].[standard-phrases-window-and-history-window]._index": typeof import("./app/routes/[jp].[docs].[standard-phrases-window-and-history-window]._index.tsx");
  "routes/[docs].[standard-phrases-window-and-history-window]._index": typeof import("./app/routes/[docs].[standard-phrases-window-and-history-window]._index.tsx");
  "routes/[jp].[docs].[export-and-import-of-standard-phrases]._index": typeof import("./app/routes/[jp].[docs].[export-and-import-of-standard-phrases]._index.tsx");
  "routes/[jp].[docs].[standard-phrases-and-copy-history]._index": typeof import("./app/routes/[jp].[docs].[standard-phrases-and-copy-history]._index.tsx");
  "routes/[docs].[export-and-import-of-standard-phrases]._index": typeof import("./app/routes/[docs].[export-and-import-of-standard-phrases]._index.tsx");
  "routes/[docs].[standard-phrases-and-copy-history]._index": typeof import("./app/routes/[docs].[standard-phrases-and-copy-history]._index.tsx");
  "routes/[jp].[docs].[how-to-use-quick-overlay]._index": typeof import("./app/routes/[jp].[docs].[how-to-use-quick-overlay]._index.tsx");
  "routes/[jp].[docs].[upgrade-history-data]._index": typeof import("./app/routes/[jp].[docs].[upgrade-history-data]._index.tsx");
  "routes/[docs].[how-to-use-quick-overlay]._index": typeof import("./app/routes/[docs].[how-to-use-quick-overlay]._index.tsx");
  "routes/[docs].[upgrade-history-data]._index": typeof import("./app/routes/[docs].[upgrade-history-data]._index.tsx");
  "routes/[jp].[docs].[notifications]._index": typeof import("./app/routes/[jp].[docs].[notifications]._index.tsx");
  "routes/[jp].[docs].[useful-usages]._index": typeof import("./app/routes/[jp].[docs].[useful-usages]._index.tsx");
  "routes/[docs].[notifications]._index": typeof import("./app/routes/[docs].[notifications]._index.tsx");
  "routes/[docs].[useful-usages]._index": typeof import("./app/routes/[docs].[useful-usages]._index.tsx");
  "routes/[jp].[docs].[settings]._index": typeof import("./app/routes/[jp].[docs].[settings]._index.tsx");
  "routes/[jp].[privacy-policy]._index": typeof import("./app/routes/[jp].[privacy-policy]._index.tsx");
  "routes/[jp].[release-notes]._index": typeof import("./app/routes/[jp].[release-notes]._index.tsx");
  "routes/[jp].[docs].[news]._index": typeof import("./app/routes/[jp].[docs].[news]._index.tsx");
  "routes/[docs].[settings]._index": typeof import("./app/routes/[docs].[settings]._index.tsx");
  "routes/[jp].[docs].[faq]._index": typeof import("./app/routes/[jp].[docs].[faq]._index.tsx");
  "routes/[privacy-policy]._index": typeof import("./app/routes/[privacy-policy]._index.tsx");
  "routes/[release-notes]._index": typeof import("./app/routes/[release-notes]._index.tsx");
  "routes/[jp].[support]._index": typeof import("./app/routes/[jp].[support]._index.tsx");
  "routes/[docs].[news]._index": typeof import("./app/routes/[docs].[news]._index.tsx");
  "routes/[sitemap.xml]._index": typeof import("./app/routes/[sitemap.xml]._index.tsx");
  "routes/[docs].[faq]._index": typeof import("./app/routes/[docs].[faq]._index.tsx");
  "routes/[jp].[docs]._index": typeof import("./app/routes/[jp].[docs]._index.tsx");
  "routes/[support]._index": typeof import("./app/routes/[support]._index.tsx");
  "routes/[docs]._index": typeof import("./app/routes/[docs]._index.tsx");
  "routes/[robots.txt]": typeof import("./app/routes/[robots.txt].tsx");
  "routes/[jp]._index": typeof import("./app/routes/[jp]._index.tsx");
  "routes/[_image].$": typeof import("./app/routes/[_image].$.ts");
  "routes/[jp].$": typeof import("./app/routes/[jp].$.tsx");
  "routes/_index": typeof import("./app/routes/_index.tsx");
  "routes/$": typeof import("./app/routes/$.tsx");
};