// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/jp/privacy-policy": {
    params: {};
  };
  "/jp/release-notes": {
    params: {};
  };
  "/privacy-policy": {
    params: {};
  };
  "/release-notes": {
    params: {};
  };
  "/jp/support": {
    params: {};
  };
  "/sitemap.xml": {
    params: {};
  };
  "/support": {
    params: {};
  };
  "/robots.txt": {
    params: {};
  };
  "/jp": {
    params: {};
  };
  "/_image/*": {
    params: {
      "*": string;
    };
  };
  "/*": {
    params: {
      "*": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/jp/privacy-policy" | "/jp/release-notes" | "/privacy-policy" | "/release-notes" | "/jp/support" | "/sitemap.xml" | "/support" | "/robots.txt" | "/jp" | "/_image/*" | "/*";
  };
  "routes/[jp].[privacy-policy]._index.tsx": {
    id: "routes/[jp].[privacy-policy]._index";
    page: "/jp/privacy-policy";
  };
  "routes/[jp].[release-notes]._index.tsx": {
    id: "routes/[jp].[release-notes]._index";
    page: "/jp/release-notes";
  };
  "routes/[privacy-policy]._index.tsx": {
    id: "routes/[privacy-policy]._index";
    page: "/privacy-policy";
  };
  "routes/[release-notes]._index.tsx": {
    id: "routes/[release-notes]._index";
    page: "/release-notes";
  };
  "routes/[jp].[support]._index.tsx": {
    id: "routes/[jp].[support]._index";
    page: "/jp/support";
  };
  "routes/[sitemap.xml]._index.tsx": {
    id: "routes/[sitemap.xml]._index";
    page: "/sitemap.xml";
  };
  "routes/[support]._index.tsx": {
    id: "routes/[support]._index";
    page: "/support";
  };
  "routes/[robots.txt].tsx": {
    id: "routes/[robots.txt]";
    page: "/robots.txt";
  };
  "routes/[jp]._index.tsx": {
    id: "routes/[jp]._index";
    page: "/jp";
  };
  "routes/[_image].$.ts": {
    id: "routes/[_image].$";
    page: "/_image/*";
  };
  "routes/_index.tsx": {
    id: "routes/_index";
    page: "/";
  };
  "routes/$.tsx": {
    id: "routes/$";
    page: "/*";
  };
};